config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: "home#index", as: "home"
  end
  unauthenticated :user do
    root 'static_pages#index'
  end

  resources :tweets, except: [:new, :edit] do
    member do
      post :reply
    end
  end
  resources :users, except: [:new, :create] do
    member do
      get 'followers'
      get 'following'
      get 'favorites'
      get 'retweets'
    end
  end

  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :retweets, only: [:create, :destroy]
  resources :find_friends, only: :index

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :tweet
  belongs_to :user
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  before_action :authenticate_user!

  def create
    @favorite = Favorite.new(tweet_id: params[:tweet_id], user: current_user)
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @favorite = Favorite.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

end

app/views/favorites/_favorite_button.html.erb
<% if tweet_favored?(tweet_id) %>
  <%= link_to favorite_path(get_favorite(tweet_id)), method: :delete, remote: true, class: "favored" do %>
    <i class="fa fa-star"></i>
  <% end %>
<% else %>
  <%= link_to favorites_path(tweet_id: tweet_id), method: :post, remote: true do %>
    <i class="fa fa-star"></i>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
<% if @favorite.save %>
  $("#favor-tweet-<%= @favorite.tweet_id %>").html("<%=j render('favorites/favorite_button', tweet_id: @favorite.tweet_id) %>");
<% else %>
  $('#tweet-error').html("<%=j render 'partials/error_message', error_message: 'Couldn\'t favour tweet. Try again?' %>");
<% end %>

app/views/favorites/destroy.js.erb
<% if @favorite.destroy %>
  $("#favor-tweet-<%= @favorite.tweet_id %>").html("<%=j render('favorites/favorite_button', tweet_id: @favorite.tweet_id) %>");
<% else %>
  $('#tweet-error').html("<%=j render 'partials/error_message', error_message: 'Something went wrong there. Try again?' %>");
<% end %>