config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: "home#index", as: "home"
  end
  unauthenticated :user do
    root 'static_pages#index'
  end

  resources :tweets, except: [:new, :edit] do
    member do
      post :reply
    end
  end
  resources :users, except: [:new, :create] do
    member do
      get 'followers'
      get 'following'
      get 'favorites'
      get 'retweets'
    end
  end

  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :retweets, only: [:create, :destroy]
  resources :find_friends, only: :index

end

app/models/retweet.rb
class Retweet < ActiveRecord::Base
  belongs_to :retweeter, class_name: "User"
  belongs_to :source_tweet, class_name: "Tweet"

  validates_presence_of :retweeter

end

app/controllers/retweets_controller.rb
class RetweetsController < ApplicationController

  before_action :authenticate_user!

  def create
    @retweet = Retweet.new(source_tweet_id: params[:tweet_id])
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @retweet = Retweet.new(params[:id])
    respond_to do |format|
      format.js
    end
  end
end

app/views/retweets/_retweet.html.erb
<div id="retweet-<%= retweet.id %>" class="micropost">
  <div class="content">
    <div class="avatar-content">
      <%= link_to retweet.source_tweet.user do %>
        <%= render 'partials/avatar', user: retweet.source_tweet.user, klass: 'avatar' %>
      <% end %>
    </div>
    <div class="post-content">
      <span class="name"><%= retweet.source_tweet.user.name %></span>
      <span class="username">@<%= retweet.source_tweet.user.username %></span>
      <div class="post">
        <%= retweet.source_tweet.tweet_text %>
      </div>
    </div>
    <div class="right-content">
      <span><%= relative_time(retweet.source_tweet.created_at) %></span>
    </div>
  </div>
  <div class="actions">
    <div class="actions-content">
      <%= link_to reply_tweet_path(retweet.id), method: :post, remote: true do %>
        <i class="fa fa-arrow-left"></i>
      <% end %>
      <span id="retweet-<%= retweet.id %>">
        <%= render 'retweets/retweet_button', tweet_id: retweet.source_tweet.id %>
      </span>
      <span id="favor-tweet-<%= retweet.id %>">
        <%= render 'favorites/favorite_button', tweet_id: retweet.id %>
      </span>
    </div>
  </div>
</div>

app/views/retweets/_retweet_button.html.erb
<% if can_retweet?(tweet_id) %>
  <% if retweeted?(tweet_id) %>
    <%= link_to retweet_path(get_retweet(tweet_id)), class: "retweeted", method: :delete, remote: true do %>
      <i class="fa fa-retweet"></i>
    <% end %>
  <% else %>
    <%= link_to retweets_path(tweet_id: tweet_id), method: :post, remote: true do %>
      <i class="fa fa-retweet"></i>
    <% end %>
  <% end %>
<% else %>
  <a href="javascript:void(0);"><i class="fa fa-retweet"></i></a>
<% end %>

app/views/retweets/create.js.erb
<% if @retweet.save %>
	$("#retweet-<%= @retweet.source_tweet_id %>").html("<%=j render('retweets/retweet_button', tweet_id: @retweet.source_tweet_id) %>");
<% else %>
  $('#tweet-error').html("<%=j render 'partials/error_message', error_message: 'Couldn\'t Retweet. Try again later' %>");
<% end %>

app/views/retweets/destroy.js.erb
$("#retweet-<%= @retweet.source_tweet_id %>").html("<%=j render('retweets/retweet_button', tweet_id: @retweet.source_tweet_id) %>");