config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: "home#index", as: "home"
  end
  unauthenticated :user do
    root 'static_pages#index'
  end

  resources :tweets, except: [:new, :edit] do
    member do
      post :reply
    end
  end
  resources :users, except: [:new, :create] do
    member do
      get 'followers'
      get 'following'
      get 'favorites'
      get 'retweets'
    end
  end

  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :retweets, only: [:create, :destroy]
  resources :find_friends, only: :index

end

app/views/partials/_avatar.html.erb
<%= link_to user_path(user) do %>
  <%= image_tag user.avatar.url || 'avatar.jpg', class: klass %>
<% end %>

app/views/partials/_devise_form_errors.html.erb
<% if resource.errors.any? %>
  <div class="alert alert-danger alert-dismissable">
  	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= resource.errors.full_messages.first %>
  </div>
<% end %>

app/views/partials/_error_message.html.erb
<% if error_message %>
  <div class="alert alert-dismissable alert-fixed alert-info">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= error_message %>
  </div>
<% end %>

app/views/partials/_follow.html.erb
<% if following?(user) %>
  <%= link_to fa_icon("check"), relationship_path(current_user.relationships.find_by_friend_id(user)), method: :delete, remote: true, class: 'btn btn-success' %>
<% else %>
  <%= link_to fa_icon("user-plus").html_safe, relationships_path(friend_id: user.id), method: :post, remote: true, class: 'btn btn-primary' %>
<% end %>

app/views/partials/_image_upload.html.erb
<div class="modal fade" id="image-upload-modal" tabindex="-1" role="dialog" aria-labelledby="imageUploadLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Media Upload</h4>
      </div>
      <div class="modal-body">
        <%= form_tag media_path, method: :post, class: "dropzone", id: "media-dropzone" do %>
          <div class="fallback">
            <%= file_field_tag :image, multiple: false %>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/partials/_load_more.html.erb
<div id="loader", class="well text-center hidden">
  <%= image_tag "ajax-loader.gif" %>
  <%= will_paginate items %>
</div>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Clon de Twitter", root_url, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <form class="navbar-form navbar-left" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Buscar">
            </div>
          </form>
          <li>
            <a href="#", class="profile-image dropdown-toggle" data-toggle="dropdown", role="button", aria-expanded="false">
              <%= image_tag current_user.avatar, class: "avatar-xs" %>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "#{current_user.name}<br><b>@#{current_user.username}</b>".html_safe, user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to("Busca amigos", find_friends_path) %></li>
              <li><%= link_to "Configuración", user_path(current_user) %></li>
              <li><%= link_to('Salir', destroy_user_session_path, method: :delete) %></li>
            </ul>
          </li>
          <form class="navbar-form navbar-right">
            <button id="new-tweet" type="button" data-toggle="modal" data-target="#new-tweet-modal" class="btn btn-primary"><i class="fa fa-paper-plane"></i> Tweet</button>
          </form>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/partials/_new_tweet.html.erb
<%= form_tag tweets_path(parent_id: tweet_id), multipart: true, method: :post, remote: true do %>
  <div class="form-group">
    <%= text_area_tag "tweet[tweet_text]", nil, class: "form-control", placeholder: "Escribe un Tweet de 140 caracteres" %>
  </div>
  <div class="form-group hidden">
    <img id="tweet-img-preview">
    <a id="remove-tweet-img" href="#">&times;</a>
  </div>
  <div class="form-group">
    <%= hidden_field_tag "tweet[location]", nil %>
  </div>
  <div class="form-group">
    <%= file_field_tag "tweet[media]", class: "hidden", id: "media-upload-btn" %>
    <%= button_tag id: "tweet", class: "btn btn-primary" do %>
      <%= fa_icon "paper-plane" %> Tweet
    <% end %>
    <div class="pull-right">
      <span id="tweet-count">140</span>
      <a id="ps-media-upload-btn" href="javascript:void(0);" class="btn btn-default">
        <i class="fa fa-camera"></i>
      </a>
      <a id="location-btn" href="#" class="btn btn-default">
        <i class="fa fa-map-marker"></i>
      </a>
    </div>
  </div>
<% end %>
<div id="tweet-error">
  <%= render 'partials/error_message', error_message: nil %>
</div>

app/views/partials/_reply_tweet.html.erb
<div class="row">
  <div class="col-lg-10 col-lg-offset-1">
    <%= form_tag tweets_path(parent: tweet), method: :post, remote: true do %>
      <div class="form-group">
        <%= text_area_tag 'tweet[tweet_text]', "@#{tweet.user.username}", class: 'form-control', placeholder: 'Enter Reply' %>
      </div>
      <div class="form-group">
        <%= submit_tag 'Reply', id: 'tweet', class: 'btn btn-primary' %>
        <%= link_to 'Cancel', '#', class: 'btn btn-primary cancel-reply', onclick: 'removeParent(this);', "data-tweet": tweet.id %>
      </div>
    <% end %>
  </div>
</div>

app/views/partials/_tweet_modal.html.erb
<div class="modal fade" id="new-tweet-modal" tabindex="-1" role="dialog" aria-labelledby="new-tweet-label" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Compose New Tweet</h4>
      </div>
      <div class="modal-body">
        <%= render 'partials/new_tweet', tweet_id: nil %>
      </div>
    </div>
  </div>
</div>

app/views/partials/_user_info.html.erb
<div class="card">
  <div class="cover" data-cover="<%= user.cover %>">
    <%= image_tag user.avatar, class: "avatar" %>
  </div>
  <div class="about">
    <h3 class="name"><%= user.name %></h3>
    <h5 class="username"><b>@<%= user.username %></b></h5>
    <span class="content"><%= user.about %></span>
    <% if view_type == 'profile' %>
      <div class="row">
        <% unless @user.location.blank? %>
          <h5><i class="fa fa-map-marker"></i> <%= @user.location %></h5>
        <% end %>
        <% unless @user.website.blank? %>
          <h5><i class="fa fa-link"></i> <%= link_to @user.website, @user.website %></h5>
        <% end %>
        <h5><i class="fa fa-clock-o"></i> Joined <%= formatted_time(@user.created_at) %></h5>
      </div>
    <% else %>
      <div class="stats">
        <div class="row">
          <div class="col-lg-4 text-center">
            <%= link_to user_path(user) do %>
              <h5><b>Tweets</b></h5>
              <h4 id="tweets-count"><%= user.tweets_count %></h4>
            <% end %>
          </div>
          <div class="col-lg-4 text-center">
            <%= link_to followers_user_path(user) do %>
              <h5><b>Seguidores</b></h5>
              <h4 id="followers-count"><%= user.followers_count %></h4>
            <% end %>
          </div>
          <div class="col-lg-4 text-center">
            <%= link_to following_user_path(user) do %>
              <h5><b>Siguiendo</b></h5>
              <h4 id="following-count"><%= user.following_count %></h4>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>