config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  authenticated :user do
    root to: "home#index", as: "home"
  end
  unauthenticated :user do
    root 'static_pages#index'
  end

  resources :tweets, except: [:new, :edit] do
    member do
      post :reply
    end
  end
  resources :users, except: [:new, :create] do
    member do
      get 'followers'
      get 'following'
      get 'favorites'
      get 'retweets'
    end
  end

  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :retweets, only: [:create, :destroy]
  resources :find_friends, only: :index

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  attr_accessor :login

  self.per_page = 20

  extend FriendlyId
  friendly_id :username, use: [:slugged, :finders]

  devise :database_authenticatable, :registerable, :confirmable,
    :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true, length: { maximum: 100 }
  validates :username, presence: true, length: { maximum: 20 }, :uniqueness => { case_sensitive: false }

  has_many :tweets
  has_many :relationships
  has_many :friends, through: :relationships
  has_many :inverse_relationships, class_name: "Relationship", foreign_key: "friend_id"
  has_many :inverse_friends, through: :inverse_relationships, source: :user
  has_many :favorites
  has_many :retweets, foreign_key: "retweeter_id"

  mount_uploader :avatar, AvatarUploader
  mount_uploader :cover, CoverUploader

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user
  before_action :check_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  def show
    @tweets = @user.tweets.paginate(page: params[:page]).order('created_at DESC')
    respond_to do |format|
      format.js
      format.html
    end
  end

  def update
    @user.update(user_params)
    if @user.save
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def destroy
  end

  def followers
    @followers = @user.inverse_friends.paginate(page: params[:page])
    respond_to do |format|
      format.js
      format.html
    end
  end

  def following
    @following = @user.friends.paginate(page: params[:page])
    respond_to do |format|
      format.js
      format.html
    end
  end

  def favorites
    @favorites = @user.tweets.joins(:favorites).paginate(page: params[:page])
    respond_to do |format|
      format.js
      format.html
    end
  end

  def retweets
    @retweets = @user.retweets.paginate(page: params[:page]).order('created_at DESC')
    respond_to do |format|
      format.js
      format.html
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :username, :password,
                                 :about, :location, :website, :avatar, :cover)
  end

  def check_user
    if @user != current_user
      redirect_to root_path
    end
  end

  def set_user
    @user = User.friendly.find(params[:id])
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def user_cover(user)
    if user.cover.url
      "background-image: url(#{ user.cover.url})"
    else
      "background: #ccc"
    end
  end

  def following?(user)
    !current_user.friends.find_by_id(user).nil?
  end

  def follows_you?(user)
    !user.friends.find_by_id(current_user).nil?
  end

  def relative_time(created_at)
    time_ago_in_words(created_at)
  end

  def formatted_time(created_at)
    created_at.strftime("%b %d, %Y")
  end

end

app/views/users/_user.html.erb
<div class="row">
  <div class="col-lg-2">
    <%= render 'partials/avatar', user: user, klass: 'avatar-md' %>
  </div>
  <div class="col-lg-7">
    <%= link_to user_path(user) do %>
      <h5><%= user.name %> <b>@<%= user.username %></b></h5>
    <% end %>
    <h5><%= user.about || "No Bio." %></h5>
  </div>
  <div class="col-lg-3">
    <div id="relation-<%= user.id %>" class="right" style="margin-top: 10px;">
      <%= render 'partials/follow', user: user %>
    </div>
  </div>
</div>
<br>
<br>

app/views/users/_user_nav.html.erb
<div class="row">
  <div class="col-lg-12">
    <div id="user-nav" class="well">
      <div class="row">
        <div class="col-lg-6 col-lg-offset-3">
          <ul class="nav nav-pills">
            <li class="<%= view_type=='profile' ? 'active' : ''%>">
              <%= link_to "Tweets", user_path(@user) %>
            </li>
            <li class="<%= view_type=='following' ? 'active' : ''%>">
              <%= link_to "Siguiendo", following_user_path(@user) %>
            </li>
            <li class="<%= view_type=='followers' ? 'active' : ''%>">
              <%= link_to "Seguidores", followers_user_path(@user) %>
            </li>
            <li class="<%= view_type=='favorites' ? 'active' : ''%>">
              <%= link_to "Favoritos", favorites_user_path(@user) %>
            </li>
            <li class="<%= view_type=='retweets' ? 'active' : ''%>">
              <%= link_to "Retweets", retweets_user_path(@user) %>
            </li>
          </ul>
        </div>
        <div class="col-lg-2 col-lg-offset-1">
          <%= label_tag 'Follows you', nil if follows_you?(@user) %>
          <% if @user == current_user %>
            <%= link_to "Editar Perfil", edit_user_path(@user), class: 'btn btn-default' %>
          <% else %>
            <div id="relation-<%= @user.id %>">
              <%= render 'partials/follow', user: @user %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<% if resource.errors.any? %>
  <div class="alert alert-danger alert-dismissable alert-fixed">
    <%= resource.errors.full_messages.first %>
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  </div>
<% end %>
<div class="tw-form row">
  <div class="col-lg-6 col-lg-offset-3">
    <div class="well">
      <h4><b>Editar Perfil</b></h4>
      <div class="row">
        <div class="col-lg-10 col-lg-offset-1">
          <%= form_for @user do |f| %>
            <div class="form-group">
              <%= f.label :avatar %><br>
              <%= render 'partials/avatar', user: @user, klass: 'avatar-lg' %><br>
              <br>
              <%= f.file_field :avatar %>
            </div>
            <div class="form-group">
              <%= f.label :fondo %><br>
              <%= image_tag @user.cover, style: 'width: 400px;' %><br>
              <br>
              <%= f.file_field :cover %>
            </div>
            <div class="form-group">
              <%= f.label :nombre %>
              <%= f.text_field :name, placeholder: 'name', class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :usuario %>
              <%= f.text_field :username, placeholder: 'username', class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label "a cerca de mi" %>
              <%= f.text_area :about, placeholder: 'a cerca de mi', class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :localización %>
              <%= f.text_field :location, placeholder: 'localización', class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label "Sitio web" %>
              <%= f.text_field :website, placeholder: 'sitio web', class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= submit_tag "Actualiza", class: 'btn btn-primary' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/favorites.html.erb
<div style="<%= user_cover(@user) %>" class="cover-pic">
</div>
<%= render 'user_nav', view_type: 'favorites' %>
<div class="row">
  <div class="col-lg-3">
    <%= render 'partials/user_info', view_type: 'profile', user: @user %>
  </div>
  <div class="col-lg-6">
    <div id="content">
      <div id="feed" class="well feed">
        <%= render(@favorites) || "No Favorites" %>
      </div>
      <div id="load-more">
        <%= render 'partials/load_more', items: @favorites %>
      </div>
    </div>
  </div>
  <div class="col-lg-3">
    <div class="well"></div>
  </div>
</div>

app/views/users/favorites.js.erb
$('#feed').append("<%= j render @favorites %>");

<% if @favorites.next_page %>
  $(".pagination").replaceWith("<%= j will_paginate(@favorites) %>");
  $(".pagination").hide();
<% else %>
  $(window).off('scroll');
  $("#loader").remove();
  $(".pagination").remove();
<% end %>

app/views/users/followers.html.erb
<div style="<%= user_cover(@user) %>" class="cover-pic">
</div>
<%= render 'user_nav', view_type: 'followers' %>
<div class="row">
  <div class="col-lg-3">
    <%= render 'partials/user_info', view_type: 'profile', user: @user %>
  </div>
  <div class="col-lg-6">
    <div id="content" class="tw-form">
      <div id="feed" class="well">
        <h4><b>Followers</b></h4>
        <div class="row">
          <div class="col-lg-10 col-lg-offset-1">
            <%= render(@followers) || "No Followers" %>
          </div>
        </div>
      </div>
      <div id="load-more">
        <%= render 'partials/load_more', items: @followers %>
      </div>
    </div>
  </div>
  <div class="col-lg-3">
    <div class="well"></div>
  </div>
</div>

app/views/users/followers.js.erb
$('#feed').append("<%= j render @followers %>");

<% if @followers.next_page %>
  $(".pagination").replaceWith("<%= j will_paginate(@followers) %>");
  $(".pagination").hide();
<% else %>
  $(window).off('scroll');
  $("#loader").remove();
  $(".pagination").remove();
<% end %>

app/views/users/following.html.erb
<div style="<%= user_cover(@user) %>" class="cover-pic">
</div>
<%= render 'user_nav', view_type: 'following' %>
<div class="row">
  <div class="col-lg-3">
    <%= render 'partials/user_info', view_type: 'profile', user: @user %>
  </div>
  <div class="col-lg-6">
    <div id="content" class="tw-form">
      <div id="feed" class="well">
        <h4><b>Following</b></h4>
        <div class="row">
          <div class="col-lg-10 col-lg-offset-1">
            <%= render(@following) || "Not Following anyone." %>
          </div>
        </div>
      </div>
      <div id="load-more">
        <%= render 'partials/load_more', items: @following %>
      </div>
    </div>
  </div>
  <div class="col-lg-3">
    <div class="well"></div>
  </div>
</div>

app/views/users/following.js.erb
$('#feed').append("<%= j render @following %>");

<% if @following.next_page %>
  $(".pagination").replaceWith("<%= j will_paginate(@following) %>");
  $(".pagination").hide();
<% else %>
  $(window).off('scroll');
  $("#loader").remove();
  $(".pagination").remove();
<% end %>

app/views/users/retweets.html.erb
<div style="<%= user_cover(@user) %>" class="cover-pic">
</div>
<%= render 'user_nav', view_type: 'retweets' %>
<div class="row">
  <div class="col-lg-3">
    <%= render 'partials/user_info', view_type: 'profile', user: @user %>
  </div>
  <div class="col-lg-6">
    <div id="content">
      <div id="feed" class="well feed">
        <%= render(@retweets) || "No Retweets" %>
      </div>
      <div id="load-more">
        <%= render 'partials/load_more', items: @retweets %>
      </div>
    </div>
  </div>
  <div class="col-lg-3">
    <div class="well"></div>
  </div>
</div>

app/views/users/retweets.js.erb
$('#feed').append("<%= j render @retweets %>");

<% if @retweets.next_page %>
  $(".pagination").replaceWith("<%= j will_paginate(@retweets) %>");
  $(".pagination").hide();
<% else %>
  $(window).off('scroll');
  $("#loader").remove();
  $(".pagination").remove();
<% end %>

app/views/users/show.html.erb
<div style="<%= user_cover(@user) %>" class="cover-pic">
</div>
<%= render 'user_nav', view_type: 'profile' %>
<div class="row">
  <div class="col-lg-3">
    <%= render 'partials/user_info', view_type: 'profile', user: @user %>
  </div>
  <div class="col-lg-6">
    <div id="content">
      <div id="feed" class="well feed">
        <%= render(@tweets) || "Ningún Tweet" %>
      </div>
      <div id="load-more">
        <%= render 'partials/load_more', items: @tweets %>
      </div>
    </div>
  </div>
  <div class="col-lg-3">
    <div class="well"></div>
  </div>
</div>

app/views/users/show.js.erb
$('#feed').append("<%= j render @tweets %>");

<% if @tweets.next_page %>
  $(".pagination").replaceWith("<%= j will_paginate(@tweets) %>");
  $(".pagination").hide();
<% else %>
  $(window).off('scroll');
  $("#loader").remove();
  $(".pagination").remove();
<% end %>